// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: cmd/004-grpc/model/messages.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operand1 int64 `protobuf:"varint,1,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operant2 int64 `protobuf:"varint,2,opt,name=operant2,proto3" json:"operant2,omitempty"`
}

func (x *MathRequest) Reset() {
	*x = MathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_004_grpc_model_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathRequest) ProtoMessage() {}

func (x *MathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_004_grpc_model_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathRequest.ProtoReflect.Descriptor instead.
func (*MathRequest) Descriptor() ([]byte, []int) {
	return file_cmd_004_grpc_model_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MathRequest) GetOperand1() int64 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *MathRequest) GetOperant2() int64 {
	if x != nil {
		return x.Operant2
	}
	return 0
}

type MathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MathResponse) Reset() {
	*x = MathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_004_grpc_model_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathResponse) ProtoMessage() {}

func (x *MathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_004_grpc_model_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathResponse.ProtoReflect.Descriptor instead.
func (*MathResponse) Descriptor() ([]byte, []int) {
	return file_cmd_004_grpc_model_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MathResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_cmd_004_grpc_model_messages_proto protoreflect.FileDescriptor

var file_cmd_004_grpc_model_messages_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6d, 0x64, 0x2f, 0x30, 0x30, 0x34, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x45, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74,
	0x32, 0x22, 0x26, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3d, 0x0a, 0x0b, 0x4d, 0x61, 0x74,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12,
	0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_004_grpc_model_messages_proto_rawDescOnce sync.Once
	file_cmd_004_grpc_model_messages_proto_rawDescData = file_cmd_004_grpc_model_messages_proto_rawDesc
)

func file_cmd_004_grpc_model_messages_proto_rawDescGZIP() []byte {
	file_cmd_004_grpc_model_messages_proto_rawDescOnce.Do(func() {
		file_cmd_004_grpc_model_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_004_grpc_model_messages_proto_rawDescData)
	})
	return file_cmd_004_grpc_model_messages_proto_rawDescData
}

var file_cmd_004_grpc_model_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_004_grpc_model_messages_proto_goTypes = []interface{}{
	(*MathRequest)(nil),  // 0: model.MathRequest
	(*MathResponse)(nil), // 1: model.MathResponse
}
var file_cmd_004_grpc_model_messages_proto_depIdxs = []int32{
	0, // 0: model.MathService.Add:input_type -> model.MathRequest
	1, // 1: model.MathService.Add:output_type -> model.MathResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_004_grpc_model_messages_proto_init() }
func file_cmd_004_grpc_model_messages_proto_init() {
	if File_cmd_004_grpc_model_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_004_grpc_model_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_004_grpc_model_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_004_grpc_model_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_004_grpc_model_messages_proto_goTypes,
		DependencyIndexes: file_cmd_004_grpc_model_messages_proto_depIdxs,
		MessageInfos:      file_cmd_004_grpc_model_messages_proto_msgTypes,
	}.Build()
	File_cmd_004_grpc_model_messages_proto = out.File
	file_cmd_004_grpc_model_messages_proto_rawDesc = nil
	file_cmd_004_grpc_model_messages_proto_goTypes = nil
	file_cmd_004_grpc_model_messages_proto_depIdxs = nil
}
