version: '3'

services:

  caddy:
    image: gcalvocr/micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:  
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  front-end:
    image: gcalvocr/front-end:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: 'http://backend'

  broker-service:
    image: "gcalvocr/broker-service:1.0.1"
    # ports:
    #  - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: "gcalvocr/listener-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: "gcalvocr/authentication-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  
  logger-service:
    image: "gcalvocr/logger-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
  
  mailer-service:
    image: "gcalvocr/mail-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIL: localhost
      MAIL_HOST: mailhog
      PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: "Gabriel Calvo"
      FROM_ADDRESS: "gabriel.calvo@example.com"
  
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
     - "5672:5672"
    deploy:
      mode: global

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports: 
     - "1025:1025"
     - "8025:8025" # web interface
    deploy:
      mode: global

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
     - "27017:27017"
    environment:
      MONGO_INIT_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
     - ./db-data/mongo:/data/db

  postgres:
    image: 'postgres:14.2'
    ports:
     - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/posgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config:

  